apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-config
  labels:
  {{- include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}
  POSTGRES_PASSWORD: {{ .Values.config.postgresPassword | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}
  SUPERSET_POSTGRES_DB: {{ .Values.config.supersetDbname | quote }}
  SUPERSET_POSTGRES_USER: {{ .Values.config.supersetDbuser | quote }}
  SUPERSET_POSTGRES_PASSWORD: {{ .Values.config.supersetDbPassword | quote }}