apiVersion: v1
kind: Service
metadata:
  name: netbox-superset-postgres
  labels:
  {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.type }}
  selector:
    app: postgres
  {{- include "postgres.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.postgres.ports | toYaml | nindent 2 -}}
