apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis-cache.fullname" . }}-data-pvc
  labels:
  {{- include "redis-cache.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.dataPvc.storageRequest | quote }}