apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}-redis
  labels:
  {{- include "redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
    {{- include "redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: redis
      {{- include "redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - sh
        - -c
        - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - secretRef:
            name: {{ include "redis.fullname" . }}-secret
        image: {{ .Values.redis.redis.image.repository }}:{{ .Values.redis.redis.image.tag
          | default .Chart.AppVersion }}
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ include "redis.fullname" . }}-data-pvc