apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netbox.fullname" . }}-media-files-pvc
  labels:
  {{- include "netbox.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mediaFilesPvc.storageRequest | quote }}