apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netbox.fullname" . }}-reports-files-pvc
  labels:
  {{- include "netbox.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.reportsFilesPvc.storageRequest | quote }}